//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _3Tablas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Direccion
    {
        public int Id { get; set; }
        public string Calle { get; set; }
        public string Colonia { get; set; }
        public int Cp { get; set; }
        public string NumInterior { get; set; }
        public string NumExterior { get; set; }
        public int IdPersona { get; set; }
    
        public virtual Personas Personas { get; set; }
    }
}
